spring:
  application:
    name: crawler

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 0

httpClient:
  connectTimeout.milliseconds : 10000
  writeTimeout.milliseconds: 10000
  readTimeout.milliseconds: 10000
  retryNum: 2
